---
- hosts: elasticSiem
  become: yes
  gather_facts: yes

  tasks: 
    - name: Set server port in kibana file.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '^#server.port'
        line: 'server.port: {{ kibana_port }}'
  
    - name: Set server name.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#server.name'
        line: 'server.name: {{ ansible_hostname }}'

    - name: Set listening ip address.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#server.host'
        line: 'server.host: {{ node_ip }}'

    - name: Set url for kibana.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://{{ node_ip }}:{{ elastic_port }}"]'

    - name: Start Kibana service.
      service:
        name: kibana
        enabled: true
        state: started
