---
- hosts: elasticSiem
  become: yes
  gather_facts: yes
  vars:
    ens33_ip: ansible_facts['networking']['interfaces']['ens33']['bindings']['address']

  tasks: 
    - name: Set server port in kibana file.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '^#server.port'
        line: 'server.port: 5601'
  
    - name: Set server name.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#server.name'
        line: '#server.name: kibana'

    - name: Set listening ip address.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#server.host'
        line: 'server.host: 192.168.35.78'

    - name: Set url for kibana.
      lineinfile: 
        path: /etc/kibana/kibana.yml
        regexp: '#elasticsearch.hosts'
        line: '#elasticsearch.hosts: ["http://192.168.35.78:9200"] }}'

    - name: Start Kibana service.
      service:
        name: kibana
        enabled: true
        state: started
