---
- hosts: elasticSiem
  become: yes
  gather_facts: false
  
  tasks:
    - name: Install openjdk
      apt:
      #  name: [ "default-jer", "apt-transport-https" ]
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - default-jre
        - apt-transport-https
   
    - name: Add Apt signing key for elasticsearch
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Populate source list for elastic search
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7

    - name: Install elasticSearch and kibana
      apt:
        name: [ "elasticsearch", "kibana" ]
        state: present
        update_cache: yes
