---
- name: Add Apt signing key for elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Populate source list for elastic search
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7
  when: ansible_distribution == 'Ubuntu'

- name: Install openjdk, elasticSearch
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - default-jre
    - apt-transport-https
    - elasticsearch
  when: ansible_distribution == 'Ubuntu'

- name: set up elastic repo for Centos
  template:
    src: templates/elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'CentOS'

- name: Install elasticsearch pkgs in Centos
  yum:
    name: ['epel-release', 'firewalld', 'elasticsearch']
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'

- name: Start elasticSearch service.
  service:
    name: elasticsearch
    enabled: true
    state: started

- name: Set node name in elaslic yml file.
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#node.name'
    line: 'node.name: {{ elastic_node_name }}'
  notify:
    - Restart elasticsearch

- name: Set port number in elaslic yml file.
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#http.port'
    line: 'http.port: {{ elastic_port }}'
  notify:
    - Restart elasticsearch

- name: Set cluster initial master nodes.
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#cluster.initial_master_nodes'
    line: 'cluster.initial_master_nodes: node-1'
  notify:
    - Restart elasticsearch

- name: Set IP address siem listen to.
  lineinfile:
     path: /etc/elasticsearch/elasticsearch.yml
     regexp: '#network.host'
     line: 'network.host: {{ elastic_node_ip }}'
  notify:
    - Restart elasticsearch
