---
- name: Install firewall pkgs in Centos
  yum:
    name: [ 'epel-release', 'firewalld' ]
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'

- name: Install gpg key for kibana
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == 'CentOS'

- name: Install kibana pkgs in Centos
  yum:
    name: "{{ kibana_rpm_url }}"
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'

- name: Place kibana config file
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana/yml
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'CentOS'

- name: Start Kibana service.
  service:
    name: kibana
    enabled: true
    state: started

- name: Start firewalld service.
  service:
    name: firewalld
    enabled: true
    state: started
