---
# tasks file for role1
- name: deploy elasticsearch node
  include_tasks: elasticsearch.yml
  when: ansible_facts['hostname'] == 'elasticsiem'

- name: deploy kibana node
  include_tasks: kibana.yml
  when: ansible_facts['hostname'] == 'kibana'

- name: deploy suricata
  include_tasks: suricata.yml
  when: "'nids' in group_names"
  tags: suricata

- name: deploy filebeats
  include_tasks: filebeat.yml
  when: "'nids' in group_names"

- name: deploy auditbeats
  include_tasks: auditbeat.yml
  when: "'nids' in group_names"

- name: deploy packetbeats
  include_tasks: packetbeat.yml
  when: "'nids' in group_names"

- name: enable firewall in elastic node and kibana
  include_tasks: firewall.yml
