---
- name: Add Apt signing key for elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Populate source list for elastic search
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7
  when: ansible_distribution == 'Ubuntu'

- name: Install packetbeat
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - filebeat
  when: ansible_distribution == 'Ubuntu'

- name: Install firewalld pkgs
  yum:
    name: ['epel-release', 'firewalld']
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'

- name: Install gpg key for elasticsearch
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == 'CentOS'

- name: Install packetbeat pkgs
  yum:
    name: "{{ packetbeat_rpm_url }}"
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS'

- name: Set packetbeat settings
  template:
    src: templates/packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == 'CentOS'

- name: Start packetbeat service
  service:
    name: packetbeat
    enabled: true
    state: started

- name: Start firewalld service
  service:
    name: firewalld
    enabled: true
    state: started
