---
- name: Install suricata
  yum:
    name: 'suricata'
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run suricata service
  service:
    name: 'suricata'
    enabled: true
    state: started

- name: Set config file for suricata
  template:
    src: templates/suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: suricata
    group: suricata
    mode: '0640'
  notify:
    - Restart suricata

- name: Update ruleset for suricata
  shell:
    cmd: suricata-update
