---
- name: Install suricata
  yum:
    name: 'suricata'
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run suricata service
  service:
    name: 'suricata'
    enabled: true
    state: started

- name: Place extra config file
  template:
    src: templates/suricata_extra.yaml.j2
    dest: /etc/suricata/suricata_extra.yaml
    owner: suricata
    group: suricata
    mode: '0640'

- name: Set extra config file in main suricata config
  lineinfile:
    path: /etc/suricata/suricata.yaml
    regex: '#include: include2.yaml'
    line: 'include: suricata_extra.yaml'
  notify:
    - Restart suricata

- name: Update ruleset for suricata
  shell:
    cmd: suricata-update
