---
- name: Install suricata
  yum:
    name: 'suricata'
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run suricata service
  service:
    name: 'suricata'
    enabled: true
    state: started

- name: Set community-id to true
  lineinfile:
    path: /etc/suricata/suricata.yaml
    regex: 'community-id: false'
    line: '        community-id: true'
  notify:
    - Restart suricata

- name: Update ruleset for suricata
  shell:
    cmd: suricata-update
